logging:
  level:
    ROOT: INFO
    org.springframework: ERROR
    org.hibernate: ERROR
    com.kg.springbootng7: ALL
  
  pattern:
    console: "- %msg%n"
    file: "*[%-5p]-- %m--%n"
  file: logs/springbootng7.log
server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:file:~/springbootng7
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /db
  jpa:
    hibernate:
      ddl-auto: create-drop  